<div class="test">
    <div class="health-freereport">
        <h3><?php echo $this->__('Thank you for requesting your three free reports') ?></h3>
        <p><?php echo $this->__('You can download your three reports by clicking the links below:') ?></p>
        <ul>
            <li><a style="text-align: center" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'docs/Nutrition_for_Womens_Health.pdf'; ?>"><?php echo $this->__("Nutrition for Women's Health") ?></a></li>
            <li><a style="text-align: center" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'docs/Womens_General_Health.pdf'; ?>"><?php echo $this->__("Women's General Health") ?></a></li>
            <li><a style="text-align: center" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'docs/Interview_with_Dr_M_Glenville.pdf'; ?>"><?php echo $this->__("The 3 Steps to Good Health") ?></a></li>
        </ul>
        <a target="_blank" class="adobe-download" href="http://www.adobe.com/products/acrobat/readstep2.html"><?php echo $this->__('Download the Adobe Acrobat Reader Free') ?></a>
    <div align="center"><small><i><?php echo $this->__('We promise never to sell, rent or share your private details with anyone.') ?></i></small></div>
    </div>
</div>
