<?php 
//    $_items = $this->getReviewsCollection()->getItems();
//    if( count( $_items ) )
//    {
//        foreach( $_items as $_review ){
//        // Get the Review Title
//        echo $this->htmlEscape( $_review->getTitle() );
//        // Get the Review Content
//        echo $this->htmlEscape( $_review->getDetail() );
//        // Get the Review Author
//        echo $this->htmlEscape( $_review->getNickname() );
//        } 
//    } 
?>